baseURL = "https://mesmur.github.io/blog/"

languageCode = 'en-us'
title = 'M Writes'
theme = 'typo'

pluralizeListTitles = false

[taxonomies]
tag = 'tags'

[params]
description = "Just another software engineer trying to write"

# Appearance settings
theme = 'dark'
colorPalette = 'eink'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hello'
homeIntroContent = """
I'm Maahir, a software engineer and aspiring writer.

I write about... well I'm not sure if I have a niche at the moment since I've just started

There are a couple of collections I maintain:
1. [Dev](./dev) - A record of my journey as a software engineer
2. [Muse](./muse) - Personal reflections on life and random shit
"""

# Collection to display on home
homeCollection = 'dev'

# Lists parameters
paginationSize = 20
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/mesmur"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/msmur"

[[params.social]]
name = 'rss'
url = '/blog/index.xml'

# Main menu pages
[[params.menu]]
name = "home"
url = "/blog"

[[params.menu]]
name = 'dev'
url = '/blog/dev'

[[params.menu]]
name = "muse"
url = "/blog/muse"

[[params.menu]]
name = 'tags'
url = '/blog/tags'

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'


