baseURL = "https://msmur.dev/"

languageCode = 'en-us'
title = 'msmur.dev'
theme = 'typo'

pluralizeListTitles = false

[taxonomies]
tag = 'tags'
series = 'series'
category = 'categories'

[params]
description = "Just another software engineer and just another blog"

# Appearance settings
theme = 'dark'
colorPalette = 'eink'
hideHeader = false

# Favicon
faviconPath = 'img'

# Custom CSS
customCSS = ['css/style.css']

# Intro on main page, content is markdown
homeIntroTitle = 'Hey there stranger!'
homeIntroContent = """
The name's Maahir. I'm a software engineer and, in attempt to have more to my personality than software engineering, here I am trying to be a writer.

Hailing from the Pearl of the Indian Ocean (that's Sri Lanka), and currently residing in Indonesia (couldn't find a cool title) - I...

Yeah, I'm not sure where I was going with that, but now you know something about me!

I write about software engineering and other things that I find interesting.

These are the collections I maintain at the moment:
1. [Dev](./dev) - A record of my journey as a software engineer, reflections on the things I've learned, the projects I'm working on, and the occasional rant
2. [Muse](./muse) - Personal reflections on life and other attempts at being wise (although, I'm likely to come off as a sophist instead)

Look at my [now](./now) page if you're just interested in the kind of person I am :)
"""

# Collection to display on home
homeCollection = 'dev'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/mesmur"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/msmur"

[[params.social]]
name = 'goodreads'
url = 'https://www.goodreads.com/user/show/26786246-maahir-ur-rahman'

# Main menu pages
[[params.menu]]
name = "now"
url = "/now"

[[params.menu]]
name = 'dev'
url = '/dev'

[[params.menu]]
name = "muse"
url = "/muse"


[[params.taxonomyMenu]]
name = 'by tag'
url = '/tags'

[[params.taxonomyMenu]]
name = 'by series'
url = '/series'

[[params.taxonomyMenu]]
name = 'by category'
url = '/categories'


# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

[params.umami]
enable = true
websiteId = "ce9c7ddd-5c42-4c2d-956e-5350ac3656c1"
jsLocation = "https://cloud.umami.is/script.js"
